sonar.organization=organizacioniac
sonar.projectKey=CastAlX7_E-Commerce-GoldenBears
sonar.projectName=E-Commerce-GoldenBears

sonar.sources=backend,frontend,iac,ansible,bootstrap,grafana,prometheus,.github
sonar.sourceEncoding=UTF-8

sonar.inclusions=**/*.py,**/*.js,**/*.jsx,**/*.ts,**/*.tsx,**/*.tf,**/*.tfvars,**/*.yml,**/*.yaml,**/*.j2,**/Dockerfile,**/*.json

sonar.exclusions=**/.terraform/**,**/*.tfstate,**/*.tfstate.backup,**/*.tfplan,**/placeholder.zip,\
**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/*.pyc,\
frontend/package-lock.json,backend/**/build/**

sonar.scanner.skipJreProvisioning=true
