- name: Generar iac/{{ workspace }}.tfvars
  ansible.builtin.template:
    src: tfvars.j2
    dest: "{{ playbook_dir }}/../../iac/{{ workspace }}.tfvars"
    mode: '0600'

- name: Verificar que el archivo fue creado
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/../../iac/{{ workspace }}.tfvars"
  register: tfvars_file

- name: Confirmar creación
  ansible.builtin.debug:
    msg: "Archivo {{ workspace }}.tfvars creado correctamente"
  when: tfvars_file.stat.exists