apiVersion: 1

datasources:
  - name: CloudWatch
    uid: golden-bears-cloudwatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: default
      defaultRegion: us-east-1
    editable: true

  - name: Prometheus
    uid: golden-bears-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.golden-bears.local:9090
    jsonData:
      httpMethod: POST
    editable: true
