{
 "title": "08 - Lambdas (comprobantes / inventario)",
 "templating": {
  "list": [
   { "name": "workspace", "query": "dev,qa,prod" }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "namespace": "AWS/Lambda",
     "metricName": "Errors",
     "statistic": "Sum",
     "dimensions": {
      "FunctionName": "e-comerce-golden-bears-inventory-$workspace"
     },
     "region": "us-east-1",
     "queryMode": "Metrics"
    },
    {
     "namespace": "AWS/Lambda",
     "metricName": "Errors",
     "statistic": "Sum",
     "dimensions": {
      "FunctionName": "e-comerce-golden-bears-billing-$workspace"
     },
     "region": "us-east-1",
     "queryMode": "Metrics"
    }
   ]
  },
  {
   "title": "Duration (avg, p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "namespace": "AWS/Lambda",
     "metricName": "Duration",
     "statistic": "Average",
     "dimensions": {
      "FunctionName": "e-comerce-golden-bears-inventory-$workspace"
     },
     "region": "us-east-1",
     "queryMode": "Metrics"
    },
    {
     "namespace": "AWS/Lambda",
     "metricName": "Duration",
     "statistic": "p99",
     "dimensions": {
      "FunctionName": "e-comerce-golden-bears-billing-$workspace"
     },
     "region": "us-east-1",
     "queryMode": "Metrics"
    }
   ]
  },
  {
   "title": "Throttles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "namespace": "AWS/Lambda",
     "metricName": "Throttles",
     "statistic": "Sum",
     "dimensions": {
      "FunctionName": "e-comerce-golden-bears-inventory-$workspace"
     },
     "region": "us-east-1",
     "queryMode": "Metrics"
    },
    {
     "namespace": "AWS/Lambda",
     "metricName": "Throttles",
     "statistic": "Sum",
     "dimensions": {
      "FunctionName": "e-comerce-golden-bears-billing-$workspace"
     },
     "region": "us-east-1",
     "queryMode": "Metrics"
    }
   ]
  },
  {
   "title": "Excepciones — Lambda Inventario",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryMode": "Logs",
     "logGroupNames": [
      "/aws/lambda/e-comerce-golden-bears-inventory-$workspace"
     ],
     "region": "us-east-1",
     "expression": "fields @timestamp, @message | filter @message like /(?i)(error|exception|traceback)/ | sort @timestamp desc | limit 100"
    }
   ]
  },
  {
   "title": "Excepciones — Lambda Comprobantes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryMode": "Logs",
     "logGroupNames": [
      "/aws/lambda/e-comerce-golden-bears-billing-$workspace"
     ],
     "region": "us-east-1",
     "expression": "fields @timestamp, @message | filter @message like /(?i)(error|exception|traceback)/ | sort @timestamp desc | limit 100"
    }
   ]
  }
 ]
}