---
- name: Desplegar infraestructura con Terraform
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Inicializar Terraform
      command: terraform init
      args:
        chdir: ../../iac

    - name: Seleccionar workspace (si ya existe)
      command: terraform workspace select {{ workspace }}
      args:
        chdir: ../../iac
      ignore_errors: true

    - name: Crear workspace si no existe
      command: terraform workspace new {{ workspace }}
      args:
        chdir: ../../iac
      ignore_errors: true

    - name: Aplicar Terraform
      command: >
        terraform apply
        -var-file="{{ workspace }}.tfvars"
        -var="redis_auth_token={{ lookup('env', 'REDIS_AUTH_TOKEN') }}"
        -auto-approve
      args:
        chdir: ../../iac