---
- name: Generar archivo .tfvars para Terraform
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Crear archivo de variables iac/{{ workspace }}.tfvars"
      ansible.builtin.template:
        src: templates/tfvars.j2
        dest: "../../iac/{{ workspace }}.tfvars"
        mode: '0600'