"""add payment_fee to orders

Revision ID: 3c0a86358b20
Revises: 
Create Date: 2026-04-09 19:25:30.729284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0a86358b20'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('payment_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute("UPDATE orders SET payment_fee = 0.00 WHERE payment_fee IS NULL")
    op.alter_column('orders', 'payment_fee', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_fee')
    # ### end Alembic commands ###
