- name: Poblar secret nubefact_credentials
  community.aws.aws_secret:
    name: "{{ project_name }}-nubefact-credentials-{{ workspace }}"
    region: "{{ aws_region }}"
    secret: "{{ nubefact_secret | to_json }}"
  vars:
    nubefact_secret:
      nubefact_token: "{{ lookup('env', 'NUBEFACT_TOKEN') }}"
      nubefact_url: "https://api.nubefact.com/v1/each"

- name: Poblar secret redis_credentials
  community.aws.aws_secret:
    name: "{{ project_name }}-redis-credentials-{{ workspace }}"
    region: "{{ aws_region }}"
    secret: "{{ redis_secret | to_json }}"
  vars:
    redis_secret:
      redis_auth_token: "{{ lookup('env', 'REDIS_AUTH_TOKEN') }}"

- name: Poblar secret app_db_credentials
  community.aws.aws_secret:
    name: "{{ project_name }}-app-db-credentials-{{ workspace }}"
    region: "{{ aws_region }}"
    secret: "{{ app_db_secret | to_json }}"
  vars:
    app_db_secret:
      username: "{{ lookup('env', 'DB_USERNAME') }}"
      database: "{{ lookup('env', 'DB_NAME') }}"
      port: "5432"
      database_url: "{{ lookup('env', 'DATABASE_URL') }}"
      secret_key: "{{ lookup('env', 'SECRET_KEY') }}"